### ISSUE TITLE
WordPress 4.5 errors with Enfold

### ISSUE THREAD

**Issue by Frumph** [gbaumgart/enfold-wordpress-theme#1]
Notice: add_object_page is deprecated since version 4.5! Use add_menu_page() instead. in /wp-includes/functions.php on line 3662

Warning: Cannot modify header information - headers already sent by (output started at /wp-includes/functions.php:3662) in /wp-includes/pluggable.php on line 1171

**Comment by gbaumgart** [comment]
? this repos isn't meant for public. its just part of our infrastructure
